language: python
python:
  - "3.6"

sudo: false

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py27-django20
  - TOXENV=py33-django18
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py34-django20
  - TOXENV=py34-djangomaster
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py35-django20
  - TOXENV=py35-djangomaster
  - TOXENV=py36-django18
  - TOXENV=py36-django19
  - TOXENV=py36-django110
  - TOXENV=py36-django111
  - TOXENV=py36-django20
  - TOXENV=py36-djangomaster

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.5"
      env: TOXENV=py35-django20
    - python: "3.5"
      env: TOXENV=py35-djangomaster
  exclude:
    - python: "3.6"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py35-django20
    - python: "3.6"
      env: TOXENV=py35-djangomaster
  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster

install:
  - pip install tox "virtualenv<14"
  - pip install coveralls

script:
  - tox

after_script:
  - coveralls
